services:
  postgres:
    image: postgres:15
    container_name: linky-postgres
    restart: always
    ports:
      - 5339:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 8f7d2c1e
      POSTGRES_DB: linky
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: linky-redis
    restart: always
    ports:
      - '6389:6379'
    command: redis-server --requirepass 123456
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
